baseURL = "https://pkforum.m3ra.ru/"
languageCode = "ru-ru"
DefaultContentLanguage = "ru"
title = "Прикладной Концептуальный Форум"
disqusShortname = "pkforum"
buildFuture = true

[taxonomies]
  speaker = "speakers"
