baseURL = "https://xn--j1ajq.xn--p1acf/"
languageCode = "ru-ru"
DefaultContentLanguage = "ru"
title = "Прикладной Концептуальный Форум"
buildFuture = true

[params]
  description = "Трансляции мероприятий Прикладного Концептуального форума. E-mail для связи: pkforum@m3ra.ru."
  images = ["pkforum_320.jpg"]

[taxonomies]
  speaker = "speakers"

[menu]
  [[menu.main]]
    name = "Конференции"
    url = "/pkf/"
    weight = 1
  [[menu.main]]
    name = "Докладчики"
    url = "/speakers/"
    weight = 2
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Поддержка проекта"
    url = "/donates/"
    weight = 4
