steps:
# Use Kaniko cache to build Docker container image for Hugo
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/hugo
  - --cache=true
- name: 'gcr.io/${PROJECT_ID}/hugo'
  args:
  - version
