name: Build and deploy
on:
  push:
    branches:
      - trunk
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        env:
          HUGO_URL: https://github.com/gohugoio/hugo/releases/download/
          HUGO_OS_ARCH: Linux-64bit
          HUGO_VERSION: 0.103.0
        run: |
          wget -O- \
            ${HUGO_URL}v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_${HUGO_OS_ARCH}.tar.gz | \
          tar -C /usr/local/bin -xz
      - name: Build website
        run: hugo
      - name: Deploy files
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: htdocs
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

