name: Build and deploy
on:
  push:
    branches:
      - trunk
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        env:
          HUGO_URL: https://github.com/gohugoio/hugo/releases/download/
          HUGO_OS_ARCH: Linux-64bit
          HUGO_VERSION: 0.103.0
        run: |
          wget -O- \
            ${HUGO_URL}v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_${HUGO_OS_ARCH}.tar.gz | \
          tar -C /usr/local/bin -xz
      - name: Build website
        run: hugo
      - name: Setup SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
      - name: Deploy files
        run: rsync --archive --delete --stats -e 'ssh -o StrictHostKeyChecking=no' public/ ${{ secrets.REMOTE_DEST }}
